spring:
  application:
    name: sistema-de-gestion-reservas

  datasource:
    url: jdbc:mysql://localhost:3306/sigere
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

  flyway:
    enabled: false

backend:
  api:
    base-path: /api/v1
