spring:
  application:
    name: sistema-de-gestion-de-reservas

  datasource:
    url: jdbc:mysql://localhost:3306/sigere
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

backend:
  api:
    base-path: /api/v1

jwt:
  secret-key: ${SECRET_KEY:bW9kZXJuc3VpdHBlcmhhcHNmaXJlcGxhY2ViYWxhbmNlY2VydGFpbmx5d2hlbnRhaWw=}
  access-token:
    expiration: 3600000 # 1 hora