CREATE TABLE `usuario`
(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(20) NOT NULL UNIQUE,
    password VARCHAR(128) NOT NULL,
    rol VARCHAR(20)
);

CREATE TABLE token(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    token VARCHAR(1024) NOT NULL
);

ALTER TABLE cliente
ADD COLUMN usuario_id BIGINT,
ADD CONSTRAINT fk_usuario
FOREIGN KEY (usuario_id) REFERENCES usuario(id)